# **Graph Metrics (*Summary*)**

## 📦 **Package Import**

In [1]:
# python
import pandas as pd
import numpy as np
from IPython.display import display, Markdown
import sys
import os
from pathlib import Path

# algorithms4pepprotgraphs framework
sys.path.append('/home/jovyan/work/algorithms4pepprotgraphs')
from algorithms4pepprotgraphs.module.notebook import NotebookApp
from algorithms4pepprotgraphs.util.plotting import boxplot, lineplot

app = NotebookApp('.env.jupyter.AVPDiscover')
paths = app.paths()

[2025-03-26 04:59:53,083] WARNING [data_validator.py:87] Sequences with non-natural amino acids were excluded. See: /home/jovyan/work/output/Test/Test2/Log/Sequences_with_non_natural_amino_acids.csv
[2025-03-26 05:00:14,854] INFO [notebook.py:51] Setting:
dataset_path: /home/jovyan/work/algorithms4pepprotgraphs/dataset/StarPep/StarPep.csv
pdb_path: /home/jovyan/work/algorithms4pepprotgraphs/dataset/StarPep/ESMFold_pdbs
notebook_output_path: /home/jovyan/work/output/Test/Test2
sequence_analysis_path: /home/jovyan/work/algorithms4pepprotgraphs/output/Test/2025-03-22T09.44.18-Sequence_Analyzer
graph_analysis_path: /home/jovyan/work/algorithms4pepprotgraphs/output/Test/2025-03-26T04.35.25-Graph_Analyzer

## 📊 **Data Analysis**

### **Data**

In [2]:
data = pd.read_csv(app.graph_analysis['graph_metrics'])
data["distance_interval"] = data["distance_function"] + " " + data["interval"].astype(str)
data.head()

,sequence,distance_function,interval,number_of_nodes,number_of_edges,density,number_of_connected_components,diameter,degree_centrality,eigenvector_centrality,closeness_centrality,betweenness_centrality,harmonic_centrality,distance_interval
0,LQQLLFIAFRIGRRRRRRRR,euclidean,"(0, 10)",20,98,0.515789,1,4.0,0.515789,0.215785,0.622901,0.035673,13.908333,"euclidean (0, 10)"
1,LAQLLFIHFRIGRRRRRRRR,euclidean,"(0, 10)",20,99,0.521053,1,4.0,0.521053,0.215579,0.627122,0.035088,13.975000,"euclidean (0, 10)"
2,IIRILQQLLFIHFRIGRRRRRRRR,euclidean,"(0, 10)",24,122,0.442029,1,4.0,0.442029,0.195400,0.551131,0.039196,15.527778,"euclidean (0, 10)"
3,LQQLLFIHFAIGRRRRRRRR,euclidean,"(0, 10)",20,97,0.510526,1,4.0,0.510526,0.216144,0.615417,0.036842,13.816667,"euclidean (0, 10)"
4,LQQLLFIHFRAGRRRRRRRR,euclidean,"(0, 10)",20,96,0.505263,1,4.0,0.505263,0.216455,0.611196,0.037427,13.750000,"euclidean (0, 10)"

### **Distance Intervals**

In [ ]:
display(Markdown("\n".join(f"- {val}" for val in data['distance_interval'].unique())))

- euclidean (0, 10)
- euclidean (0, 15)
- euclidean (0, 20)
- canberra (0, 0.6155)
- canberra (0, 1.0142)
- canberra (0, 1.4712)
- lance_williams (0, 0.1789)
- lance_williams (0, 0.3041)
- lance_williams (0, 0.4664)
- clark (0, 0.4161)
- clark (0, 0.6813)
- clark (0, 0.983)
- soergel (0, 0.3035)
- soergel (0, 0.4664)
- soergel (0, 0.6357)
- bhattacharyya (0, 1.5158)
- bhattacharyya (0, 2.4304)
- bhattacharyya (0, 3.6452)
- angular_separation (0, 0.018)
- angular_separation (0, 0.0654)
- angular_separation (0, 0.1799)

### **Statistics (*per Metric*)**

#### **Number of nodes**

In [ ]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-number_of_nodes.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
1,angular_separation,"(0, 0.0654)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
2,angular_separation,"(0, 0.1799)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
3,bhattacharyya,"(0, 1.5158)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
4,bhattacharyya,"(0, 2.4304)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
5,bhattacharyya,"(0, 3.6452)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
6,canberra,"(0, 0.6155)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
7,canberra,"(0, 1.0142)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
8,canberra,"(0, 1.4712)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
9,clark,"(0, 0.4161)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
10,clark,"(0, 0.6813)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
11,clark,"(0, 0.983)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
12,euclidean,"(0, 10)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
13,euclidean,"(0, 15)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
14,euclidean,"(0, 20)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
15,lance_williams,"(0, 0.1789)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
16,lance_williams,"(0, 0.3041)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
17,lance_williams,"(0, 0.4664)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
18,soergel,"(0, 0.3035)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
19,soergel,"(0, 0.4664)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706
20,soergel,"(0, 0.6357)",17889,5.0,29.086869,17.395412,17.0,25.0,36.0,100.0,1.557182,5.895706

#### **Number of edges**

In [ ]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-number_of_edges.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",17889,0.0,131.775896,180.176008,34.0,78.0,157.0,3564.0,4.987818,51.642073
1,angular_separation,"(0, 0.0654)",17889,0.0,265.057633,345.840600,71.0,157.0,314.0,4454.0,3.478894,20.178841
2,angular_separation,"(0, 0.1799)",17889,2.0,408.481078,562.981247,98.0,233.0,472.0,4566.0,3.208465,14.910560
3,bhattacharyya,"(0, 1.5158)",17889,0.0,136.300967,156.351771,42.0,91.0,167.0,1327.0,2.894140,13.395798
4,bhattacharyya,"(0, 2.4304)",17889,5.0,273.748449,354.808494,74.0,164.0,316.0,2730.0,3.159808,14.767860
5,bhattacharyya,"(0, 3.6452)",17889,8.0,421.541003,576.841785,104.0,236.0,469.0,4083.0,3.184045,14.623910
6,canberra,"(0, 0.6155)",17889,0.0,129.932025,195.234814,26.0,69.0,148.0,1896.0,3.635264,19.501272
7,canberra,"(0, 1.0142)",17889,0.0,264.081782,408.965127,52.0,133.0,287.0,3336.0,3.470022,16.798042
8,canberra,"(0, 1.4712)",17889,0.0,407.514115,623.011195,80.0,203.0,433.0,4457.0,3.329091,15.378256
9,clark,"(0, 0.4161)",17889,0.0,130.231539,194.239365,27.0,69.0,149.0,1944.0,3.649773,19.863723
10,clark,"(0, 0.6813)",17889,0.0,263.683716,402.008094,53.0,136.0,292.0,3259.0,3.450428,16.713585
11,clark,"(0, 0.983)",17889,0.0,406.367265,619.503076,79.0,203.0,439.0,4350.0,3.315716,15.254495
12,euclidean,"(0, 10)",17889,8.0,134.975907,115.427091,56.0,103.0,175.0,852.0,2.072887,8.296436
13,euclidean,"(0, 15)",17889,10.0,245.418469,266.402928,83.0,163.0,293.0,2117.0,2.749025,12.276885
14,euclidean,"(0, 20)",17889,10.0,349.115210,426.966861,102.0,214.0,404.0,3457.0,3.021213,13.976986
15,lance_williams,"(0, 0.1789)",17889,0.0,128.483202,187.294772,27.0,70.0,149.0,1904.0,3.560913,18.856126
16,lance_williams,"(0, 0.3041)",17889,0.0,265.801834,408.413875,53.0,135.0,285.0,3356.0,3.472767,16.862481
17,lance_williams,"(0, 0.4664)",17889,2.0,410.552015,628.228645,81.0,203.0,433.0,4547.0,3.338669,15.463464
18,soergel,"(0, 0.3035)",17889,0.0,128.480798,187.289818,27.0,70.0,149.0,1904.0,3.560898,18.856103
19,soergel,"(0, 0.4664)",17889,0.0,265.823691,408.451095,53.0,135.0,285.0,3356.0,3.472744,16.862133
20,soergel,"(0, 0.6357)",17889,2.0,410.232545,627.796323,81.0,202.0,433.0,4547.0,3.339122,15.467458

#### **Density**

In [ ]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-density.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",17889,0.000000,0.268167,0.161756,0.145180,0.221053,0.366013,0.899141,0.850735,2.990273
1,angular_separation,"(0, 0.0654)",17889,0.000000,0.512699,0.176644,0.371661,0.488889,0.657895,0.973684,0.195862,2.185652
2,angular_separation,"(0, 0.1799)",17889,0.133333,0.732127,0.127890,0.645411,0.738384,0.831579,1.000000,-0.389560,2.973481
3,bhattacharyya,"(0, 1.5158)",17889,0.000000,0.290473,0.067570,0.239919,0.291667,0.339869,0.700000,0.042569,2.635381
4,bhattacharyya,"(0, 2.4304)",17889,0.203536,0.539249,0.089555,0.481612,0.541311,0.600000,1.000000,-0.146476,3.098110
5,bhattacharyya,"(0, 3.6452)",17889,0.385281,0.780217,0.087478,0.727513,0.786325,0.840396,1.000000,-0.451387,3.571625
6,canberra,"(0, 0.6155)",17889,0.000000,0.215519,0.078281,0.163636,0.217759,0.272727,0.509179,-0.226914,2.984826
7,canberra,"(0, 1.0142)",17889,0.000000,0.423790,0.099980,0.366387,0.435897,0.491421,0.773585,-0.697438,4.138072
8,canberra,"(0, 1.4712)",17889,0.000000,0.655201,0.102033,0.595442,0.655385,0.719368,1.000000,-0.410695,4.383323
9,clark,"(0, 0.4161)",17889,0.000000,0.219113,0.083275,0.161765,0.217949,0.281385,0.524660,-0.103058,2.746267
10,clark,"(0, 0.6813)",17889,0.000000,0.430755,0.106341,0.365576,0.444444,0.509524,0.790276,-0.706586,3.723830
11,clark,"(0, 0.983)",17889,0.000000,0.648103,0.113136,0.593407,0.666667,0.720648,0.931043,-1.190985,5.755974
12,euclidean,"(0, 10)",17889,0.062112,0.371563,0.167636,0.253333,0.333333,0.450575,1.000000,1.120331,4.243610
13,euclidean,"(0, 15)",17889,0.102723,0.575312,0.187852,0.439646,0.548173,0.692308,1.000000,0.468811,2.618410
14,euclidean,"(0, 20)",17889,0.154557,0.734042,0.174172,0.604859,0.733333,0.875000,1.000000,-0.228106,2.348984
15,lance_williams,"(0, 0.1789)",17889,0.000000,0.217107,0.063104,0.179487,0.221323,0.258730,0.500000,-0.456696,4.064778
16,lance_williams,"(0, 0.3041)",17889,0.000000,0.434398,0.079307,0.388889,0.433846,0.477124,0.900000,0.017444,4.361984
17,lance_williams,"(0, 0.4664)",17889,0.200000,0.667156,0.094554,0.604598,0.649621,0.721774,1.000000,0.477708,3.325758
18,soergel,"(0, 0.3035)",17889,0.000000,0.217104,0.063104,0.179487,0.221323,0.258730,0.500000,-0.456661,4.064739
19,soergel,"(0, 0.4664)",17889,0.000000,0.434431,0.079304,0.388889,0.433846,0.477183,0.900000,0.017782,4.361893
20,soergel,"(0, 0.6357)",17889,0.200000,0.666602,0.094565,0.604167,0.649123,0.721228,1.000000,0.475266,3.331726

#### **Betweenness centrality**

In [ ]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-betweenness_centrality.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",17889,0.0,0.029371,0.025638,0.011527,0.023097,0.039904,0.316176,2.092573,11.279730
1,angular_separation,"(0, 0.0654)",17889,0.0,0.023743,0.028456,0.007576,0.016524,0.030465,0.333333,4.302130,32.452457
2,angular_separation,"(0, 0.1799)",17889,0.0,0.015185,0.027131,0.003594,0.008187,0.015330,0.333333,5.356978,40.525865
3,bhattacharyya,"(0, 1.5158)",17889,0.0,0.047029,0.023010,0.031328,0.043124,0.058187,0.333333,1.897725,12.489053
4,bhattacharyya,"(0, 2.4304)",17889,0.0,0.030500,0.018758,0.018701,0.026181,0.036905,0.233333,2.366454,13.877480
5,bhattacharyya,"(0, 3.6452)",17889,0.0,0.011290,0.006939,0.006535,0.009487,0.015152,0.066667,1.274586,5.913509
6,canberra,"(0, 0.6155)",17889,0.0,0.025885,0.015262,0.016094,0.023605,0.033333,0.138889,1.111903,5.507368
7,canberra,"(0, 1.0142)",17889,0.0,0.018973,0.011295,0.011749,0.016340,0.023693,0.116667,1.814372,8.840983
8,canberra,"(0, 1.4712)",17889,0.0,0.015596,0.015731,0.007436,0.011624,0.018648,0.266667,4.700600,40.247463
9,clark,"(0, 0.4161)",17889,0.0,0.024172,0.014656,0.014652,0.022059,0.031502,0.133333,1.129753,5.681641
10,clark,"(0, 0.6813)",17889,0.0,0.016897,0.010354,0.010279,0.014594,0.021062,0.166667,2.121789,13.009371
11,clark,"(0, 0.983)",17889,0.0,0.006526,0.005472,0.003030,0.005229,0.008399,0.100000,2.622937,18.800658
12,euclidean,"(0, 10)",17889,0.0,0.053415,0.021822,0.036842,0.048968,0.071429,0.115497,0.290938,2.136303
13,euclidean,"(0, 15)",17889,0.0,0.023713,0.013093,0.013919,0.021978,0.032609,0.075401,0.448261,2.602259
14,euclidean,"(0, 20)",17889,0.0,0.011981,0.008689,0.005240,0.010598,0.017483,0.049104,0.650947,2.829016
15,lance_williams,"(0, 0.1789)",17889,0.0,0.038177,0.026395,0.023333,0.032951,0.046937,0.333333,3.646653,29.499035
16,lance_williams,"(0, 0.3041)",17889,0.0,0.032142,0.027001,0.018613,0.026144,0.037255,0.333333,4.888989,40.742593
17,lance_williams,"(0, 0.4664)",17889,0.0,0.018663,0.018650,0.008849,0.014652,0.023099,0.333333,5.397257,56.172133
18,soergel,"(0, 0.3035)",17889,0.0,0.038178,0.026395,0.023333,0.032951,0.046937,0.333333,3.646596,29.498209
19,soergel,"(0, 0.4664)",17889,0.0,0.032140,0.027000,0.018615,0.026144,0.037255,0.333333,4.889472,40.748103
20,soergel,"(0, 0.6357)",17889,0.0,0.018702,0.018685,0.008859,0.014652,0.023214,0.333333,5.398399,56.258438

#### **Closeness Centrality**

In [ ]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-closeness_centrality.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",17889,0.000000,0.333426,0.163726,0.218739,0.303670,0.445151,0.908092,0.437187,2.648787
1,angular_separation,"(0, 0.0654)",17889,0.000000,0.581197,0.150766,0.481559,0.568432,0.694697,0.976542,-0.164311,3.074805
2,angular_separation,"(0, 0.1799)",17889,0.133333,0.779733,0.100424,0.720803,0.783835,0.848159,1.000000,-0.643186,4.440450
3,bhattacharyya,"(0, 1.5158)",17889,0.000000,0.395652,0.062813,0.358645,0.402177,0.438813,0.794286,-0.612006,4.060898
4,bhattacharyya,"(0, 2.4304)",17889,0.267647,0.641243,0.071762,0.597631,0.641770,0.688596,1.000000,-0.213577,3.576957
5,bhattacharyya,"(0, 3.6452)",17889,0.493774,0.831490,0.065375,0.790665,0.836883,0.876527,1.000000,-0.436057,3.573208
6,canberra,"(0, 0.6155)",17889,0.000000,0.280587,0.095159,0.224044,0.294331,0.350873,0.564161,-0.682452,3.265637
7,canberra,"(0, 1.0142)",17889,0.000000,0.496971,0.104270,0.447105,0.512129,0.563730,0.782912,-1.162380,5.620786
8,canberra,"(0, 1.4712)",17889,0.000000,0.718229,0.091372,0.665759,0.719195,0.777797,1.000000,-0.748797,5.749617
9,clark,"(0, 0.4161)",17889,0.000000,0.279860,0.098026,0.217920,0.291093,0.354347,0.558296,-0.566926,2.990164
10,clark,"(0, 0.6813)",17889,0.000000,0.496102,0.108736,0.439991,0.514490,0.572292,0.807925,-1.152588,5.120805
11,clark,"(0, 0.983)",17889,0.000000,0.677994,0.111445,0.628571,0.697903,0.748965,0.931262,-1.448901,6.710397
12,euclidean,"(0, 10)",17889,0.094018,0.489470,0.153493,0.384906,0.467498,0.571930,1.000000,0.684092,3.398332
13,euclidean,"(0, 15)",17889,0.164478,0.672545,0.152315,0.566121,0.662949,0.772238,1.000000,0.148316,2.736850
14,euclidean,"(0, 20)",17889,0.223628,0.796547,0.134544,0.704812,0.801501,0.899126,1.000000,-0.419744,2.859842
15,lance_williams,"(0, 0.1789)",17889,0.000000,0.289560,0.082795,0.249041,0.297968,0.339724,0.610794,-0.679020,4.308361
16,lance_williams,"(0, 0.3041)",17889,0.000000,0.520074,0.088211,0.468538,0.514790,0.572017,0.920000,-0.151800,4.290666
17,lance_williams,"(0, 0.4664)",17889,0.233333,0.728218,0.084436,0.671159,0.714244,0.784510,1.000000,0.237312,3.140094
18,soergel,"(0, 0.3035)",17889,0.000000,0.289557,0.082794,0.249041,0.297905,0.339724,0.610794,-0.678984,4.308257
19,soergel,"(0, 0.4664)",17889,0.000000,0.520103,0.088216,0.468564,0.514819,0.572052,0.920000,-0.151904,4.290698
20,soergel,"(0, 0.6357)",17889,0.233333,0.727762,0.084460,0.670647,0.713766,0.783801,1.000000,0.236512,3.142289

#### **Degree Centrality**

In [ ]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-degree_centrality.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",17889,0.000000,0.268167,0.161756,0.145180,0.221053,0.366013,0.899141,0.850735,2.990273
1,angular_separation,"(0, 0.0654)",17889,0.000000,0.512699,0.176644,0.371661,0.488889,0.657895,0.973684,0.195862,2.185652
2,angular_separation,"(0, 0.1799)",17889,0.133333,0.732127,0.127890,0.645411,0.738384,0.831579,1.000000,-0.389560,2.973481
3,bhattacharyya,"(0, 1.5158)",17889,0.000000,0.290473,0.067570,0.239919,0.291667,0.339869,0.700000,0.042569,2.635381
4,bhattacharyya,"(0, 2.4304)",17889,0.203536,0.539249,0.089555,0.481612,0.541311,0.600000,1.000000,-0.146476,3.098110
5,bhattacharyya,"(0, 3.6452)",17889,0.385281,0.780217,0.087478,0.727513,0.786325,0.840396,1.000000,-0.451387,3.571625
6,canberra,"(0, 0.6155)",17889,0.000000,0.215519,0.078281,0.163636,0.217759,0.272727,0.509179,-0.226914,2.984826
7,canberra,"(0, 1.0142)",17889,0.000000,0.423790,0.099980,0.366387,0.435897,0.491421,0.773585,-0.697438,4.138072
8,canberra,"(0, 1.4712)",17889,0.000000,0.655201,0.102033,0.595442,0.655385,0.719368,1.000000,-0.410695,4.383323
9,clark,"(0, 0.4161)",17889,0.000000,0.219113,0.083275,0.161765,0.217949,0.281385,0.524660,-0.103058,2.746267
10,clark,"(0, 0.6813)",17889,0.000000,0.430755,0.106341,0.365576,0.444444,0.509524,0.790276,-0.706586,3.723830
11,clark,"(0, 0.983)",17889,0.000000,0.648103,0.113136,0.593407,0.666667,0.720648,0.931043,-1.190985,5.755974
12,euclidean,"(0, 10)",17889,0.062112,0.371563,0.167636,0.253333,0.333333,0.450575,1.000000,1.120331,4.243610
13,euclidean,"(0, 15)",17889,0.102723,0.575312,0.187852,0.439646,0.548173,0.692308,1.000000,0.468811,2.618410
14,euclidean,"(0, 20)",17889,0.154557,0.734042,0.174172,0.604859,0.733333,0.875000,1.000000,-0.228106,2.348984
15,lance_williams,"(0, 0.1789)",17889,0.000000,0.217107,0.063104,0.179487,0.221323,0.258730,0.500000,-0.456696,4.064778
16,lance_williams,"(0, 0.3041)",17889,0.000000,0.434398,0.079307,0.388889,0.433846,0.477124,0.900000,0.017444,4.361984
17,lance_williams,"(0, 0.4664)",17889,0.200000,0.667156,0.094554,0.604598,0.649621,0.721774,1.000000,0.477708,3.325758
18,soergel,"(0, 0.3035)",17889,0.000000,0.217104,0.063104,0.179487,0.221323,0.258730,0.500000,-0.456661,4.064739
19,soergel,"(0, 0.4664)",17889,0.000000,0.434431,0.079304,0.388889,0.433846,0.477183,0.900000,0.017782,4.361893
20,soergel,"(0, 0.6357)",17889,0.200000,0.666602,0.094565,0.604167,0.649123,0.721228,1.000000,0.475266,3.331726

#### **Eigenvector Centrality**

In [ ]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-eigenvector_centrality.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",644,0.050645,0.099120,0.031911,0.075654,0.092672,0.117184,0.275995,1.461306,6.771700
1,angular_separation,"(0, 0.0654)",5675,0.065748,0.149325,0.047418,0.119742,0.140208,0.165463,0.441019,1.766117,7.995104
2,angular_separation,"(0, 0.1799)",11001,0.093594,0.185434,0.057462,0.148040,0.171831,0.212658,0.447214,1.231974,4.932899
3,bhattacharyya,"(0, 1.5158)",1809,0.053887,0.123242,0.044091,0.095244,0.116187,0.136513,0.427869,2.461330,12.462129
4,bhattacharyya,"(0, 2.4304)",16366,0.065506,0.190690,0.061269,0.149261,0.177589,0.222560,0.445276,1.061435,4.480497
5,bhattacharyya,"(0, 3.6452)",17888,0.086342,0.203811,0.061855,0.161106,0.192580,0.238151,0.447214,0.990456,4.308528
6,canberra,"(0, 0.6155)",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,canberra,"(0, 1.0142)",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,canberra,"(0, 1.4712)",6082,0.093284,0.170589,0.051845,0.140415,0.160306,0.188176,0.447214,1.696432,7.352061
9,clark,"(0, 0.4161)",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,clark,"(0, 0.6813)",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,clark,"(0, 0.983)",1,0.387738,0.387738,NaN,0.387738,0.387738,0.387738,0.387738,NaN,NaN
12,euclidean,"(0, 10)",17888,0.047768,0.189541,0.068412,0.141463,0.176341,0.229461,0.447214,0.881511,3.914412
13,euclidean,"(0, 15)",17889,0.056259,0.199969,0.065427,0.155019,0.187323,0.237690,0.447214,0.902035,4.042299
14,euclidean,"(0, 20)",17889,0.064706,0.204740,0.063866,0.160675,0.193015,0.241568,0.447214,0.908800,4.066510
15,lance_williams,"(0, 0.1789)",1992,0.054664,0.122734,0.042792,0.093182,0.114088,0.139246,0.430940,2.327871,12.863187
16,lance_williams,"(0, 0.3041)",6138,0.079105,0.158220,0.053553,0.126647,0.146752,0.172964,0.445276,2.018086,8.545542
17,lance_williams,"(0, 0.4664)",9782,0.093763,0.182734,0.059394,0.146745,0.168387,0.204252,0.447214,1.564522,6.011042
18,soergel,"(0, 0.3035)",1992,0.054664,0.122732,0.042792,0.093182,0.114073,0.139246,0.430940,2.328043,12.864043
19,soergel,"(0, 0.4664)",6139,0.079105,0.158222,0.053548,0.126648,0.146745,0.172964,0.445276,2.018224,8.546603
20,soergel,"(0, 0.6357)",9776,0.093743,0.182701,0.059409,0.146708,0.168382,0.204155,0.447214,1.565777,6.014679

#### **Harmonic Centrality**

In [13]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-harmonic_centrality.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",17889,0.000000,11.555994,8.348273,5.998066,9.931818,15.166667,80.875421,1.532814,7.123629
1,angular_separation,"(0, 0.0654)",17889,0.000000,18.769670,12.108351,10.383333,16.477778,24.125000,91.050505,1.463789,5.964120
2,angular_separation,"(0, 0.1799)",17889,0.666667,23.774522,15.153571,13.125000,20.794872,30.158333,95.114478,1.541744,5.965499
3,bhattacharyya,"(0, 1.5158)",17889,0.000000,13.845561,8.342546,7.965079,12.353439,17.463578,53.103596,1.493621,5.957474
4,bhattacharyya,"(0, 2.4304)",17889,2.200000,20.354226,12.045641,11.842593,17.916667,25.171429,75.270408,1.574468,6.103664
5,bhattacharyya,"(0, 3.6452)",17889,3.333333,24.674721,15.038960,14.037037,21.416667,30.459459,90.260000,1.597012,6.093968
6,canberra,"(0, 0.6155)",17889,0.000000,10.833644,8.881983,4.769231,8.765152,14.259885,58.534066,1.801863,7.148522
7,canberra,"(0, 1.0142)",17889,0.000000,17.116873,12.880192,8.245614,14.277778,21.898148,79.518900,1.769512,6.820451
8,canberra,"(0, 1.4712)",17889,0.000000,22.869969,16.102640,11.541667,19.234568,28.725490,93.948454,1.679399,6.334633
9,clark,"(0, 0.4161)",17889,0.000000,10.678115,8.683611,4.782051,8.662434,14.128125,59.364103,1.776834,7.094156
10,clark,"(0, 0.6813)",17889,0.000000,16.903162,12.599939,8.244444,14.173333,21.681373,78.575258,1.743133,6.750885
11,clark,"(0, 0.983)",17889,0.000000,21.347781,15.581162,10.511111,17.884615,27.083333,89.948980,1.708543,6.494062
12,euclidean,"(0, 10)",17889,3.166667,15.338915,6.965158,10.322222,14.058333,18.712348,49.437755,1.307647,5.348899
13,euclidean,"(0, 15)",17889,4.000000,20.043352,10.414603,12.666667,17.965517,24.405263,69.391156,1.447812,5.709051
14,euclidean,"(0, 20)",17889,4.000000,23.151302,12.909465,13.933333,20.500000,28.363636,83.775510,1.495273,5.814373
15,lance_williams,"(0, 0.1789)",17889,0.000000,11.570052,9.259281,5.214583,9.383598,15.016388,58.768794,1.790995,6.987265
16,lance_williams,"(0, 0.3041)",17889,0.000000,18.275617,13.327130,8.946296,15.210606,22.948505,82.078231,1.747030,6.654813
17,lance_williams,"(0, 0.4664)",17889,1.000000,23.213560,16.079493,11.843137,19.520000,28.962963,94.929293,1.698325,6.388883
18,soergel,"(0, 0.3035)",17889,0.000000,11.569951,9.259188,5.214583,9.383598,15.016388,58.768794,1.790989,6.987246
19,soergel,"(0, 0.4664)",17889,0.000000,18.276448,13.327691,8.947917,15.210606,22.948505,82.078231,1.747018,6.654705
20,soergel,"(0, 0.6357)",17889,1.000000,23.203904,16.074457,11.843137,19.518519,28.944444,94.929293,1.698521,6.389793

#### **Number of Connected Components**

In [3]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-number_of_connected_components.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",17889,1.0,4.736542,1.932610,3.0,5.0,6.0,15.0,0.481751,3.484064
1,angular_separation,"(0, 0.0654)",17889,1.0,2.232881,1.065965,1.0,2.0,3.0,8.0,0.427564,2.398490
2,angular_separation,"(0, 0.1799)",17889,1.0,1.416457,0.553661,1.0,1.0,2.0,4.0,0.906203,2.850393
3,bhattacharyya,"(0, 1.5158)",17889,1.0,2.554028,0.856289,2.0,3.0,3.0,6.0,0.069178,2.540237
4,bhattacharyya,"(0, 2.4304)",17889,1.0,1.085136,0.279092,1.0,1.0,1.0,2.0,2.973038,9.838955
5,bhattacharyya,"(0, 3.6452)",17889,1.0,1.000056,0.007477,1.0,1.0,1.0,2.0,133.738551,17887.000056
6,canberra,"(0, 0.6155)",17889,2.0,6.453966,1.948469,5.0,6.0,8.0,17.0,0.756005,3.675856
7,canberra,"(0, 1.0142)",17889,2.0,4.048186,0.939781,3.0,4.0,5.0,9.0,0.517975,3.723388
8,canberra,"(0, 1.4712)",17889,1.0,1.849740,0.728451,1.0,2.0,2.0,6.0,0.428897,2.631015
9,clark,"(0, 0.4161)",17889,2.0,6.588630,1.991874,5.0,6.0,8.0,17.0,0.724641,3.553745
10,clark,"(0, 0.6813)",17889,2.0,4.299570,1.049843,4.0,4.0,5.0,10.0,0.500610,3.457409
11,clark,"(0, 0.983)",17889,1.0,3.581251,0.698122,3.0,4.0,4.0,7.0,-0.372862,3.182921
12,euclidean,"(0, 10)",17889,1.0,1.000056,0.007477,1.0,1.0,1.0,2.0,133.738551,17887.000056
13,euclidean,"(0, 15)",17889,1.0,1.000000,0.000000,1.0,1.0,1.0,1.0,NaN,NaN
14,euclidean,"(0, 20)",17889,1.0,1.000000,0.000000,1.0,1.0,1.0,1.0,NaN,NaN
15,lance_williams,"(0, 0.1789)",17889,1.0,4.871318,2.085357,4.0,5.0,6.0,12.0,-0.263437,2.560290
16,lance_williams,"(0, 0.3041)",17889,1.0,2.356644,1.133000,1.0,3.0,3.0,6.0,0.080339,1.768219
17,lance_williams,"(0, 0.4664)",17889,1.0,1.494997,0.577889,1.0,1.0,2.0,4.0,0.677353,2.501891
18,soergel,"(0, 0.3035)",17889,1.0,4.871373,2.085347,4.0,5.0,6.0,12.0,-0.263517,2.560365
19,soergel,"(0, 0.4664)",17889,1.0,2.356532,1.132936,1.0,3.0,3.0,6.0,0.080014,1.767352
20,soergel,"(0, 0.6357)",17889,1.0,1.495780,0.578669,1.0,1.0,2.0,4.0,0.678565,2.504973