# **Graph Metrics (*Summary*)**

## 📦 **Package Import**

In [1]:
# python
import pandas as pd
import numpy as np
from IPython.display import display, Markdown
import sys
import os
from pathlib import Path

# algorithms4pepprotgraphs framework
sys.path.append('/home/jovyan/work/PepProtGraphAnalyzer')
from PepProtGraphAnalyzer.module.notebook import NotebookApp
from PepProtGraphAnalyzer.util.plotting import boxplot

app = NotebookApp('.env.jupyter.AVPDiscover.train')
paths = app.paths()

[2025-09-23 19:39:45,347] INFO [notebook.py:70] Setting:
dataset_path: /home/jovyan/work/PepProtGraphAnalyzer/dataset/AVPDiscover/AVPDiscover-train.csv
pdb_path: /home/jovyan/work/PepProtGraphAnalyzer/dataset/AVPDiscover/ESMFold_pdbs
notebook_output_path: /home/jovyan/work/output/out_paper/AVPDiscover-train
sequence_analysis_path: /home/jovyan/work/PepProtGraphAnalyzer/output/results_with_all_seq/AVPDiscover/Train/2025-04-09T15.38.22-Sequence_Analyzer
graph_analysis_path: /home/jovyan/work/PepProtGraphAnalyzer/output/results_with_all_seq/AVPDiscover/Train/2025-04-10T03.56.24-Graph_Analyzer
min_seq_len: None
max_seq_len: None

## 📊 **Data Analysis**

### **Data**

In [2]:
data = pd.read_csv(app.graph_analysis['graph_metrics'])
data["distance_interval"] = data["distance_function"] + " " + data["interval"].astype(str)
data.head()

,sequence,distance_function,interval,number_of_nodes,number_of_edges,density,number_of_connected_components,diameter,degree_centrality,eigenvector_centrality,closeness_centrality,betweenness_centrality,harmonic_centrality,distance_interval
0,GVIPCGESCVFIPCISAAIGCSCKNKVCYRN,euclidean,"(0, 10.2836)",31,239,0.513978,1,3.0,0.513978,0.170246,0.672211,0.017798,22.559140,"euclidean (0, 10.2836)"
1,GSGPTYCWNEANNPGGPNRCSNNKQCDGARTCSSSGFCQGTSRKPD...,euclidean,"(0, 10.2836)",95,692,0.154983,1,6.0,0.154983,0.079730,0.363299,0.019181,42.497544,"euclidean (0, 10.2836)"
2,ERKVDFLEENITALLEEAQIQQEKNMYELQKLNSW,euclidean,"(0, 10.2836)",35,189,0.317647,1,6.0,0.317647,0.159239,0.421823,0.043799,19.166667,"euclidean (0, 10.2836)"
3,QEWERKVDFLEENITALLEEAQIQQEKNMYELQKL,euclidean,"(0, 10.2836)",35,190,0.319328,1,6.0,0.319328,0.159096,0.424115,0.043392,19.231429,"euclidean (0, 10.2836)"
4,WERKVDFLEENITALLEEAQIQQEKNMYELQKLNS,euclidean,"(0, 10.2836)",35,189,0.317647,1,6.0,0.317647,0.159239,0.421823,0.043799,19.166667,"euclidean (0, 10.2836)"

### **Distance Intervals**

In [3]:
display(Markdown("\n".join(f"- {val}" for val in data['distance_interval'].unique())))

- euclidean (0, 10.2836)
- euclidean (0, 16.6132)
- euclidean (0, 26.242)
- canberra (0, 0.6155)
- canberra (0, 1.0142)
- canberra (0, 1.4712)
- lance_williams (0, 0.1789)
- lance_williams (0, 0.3041)
- lance_williams (0, 0.466)
- clark (0, 0.4161)
- clark (0, 0.6813)
- clark (0, 0.983)
- soergel (0, 0.3035)
- soergel (0, 0.4664)
- soergel (0, 0.6357)
- bhattacharyya (0, 1.5158)
- bhattacharyya (0, 2.4304)
- bhattacharyya (0, 3.6452)
- angular_separation (0, 0.018)
- angular_separation (0, 0.0654)
- angular_separation (0, 0.1799)

### **Statistics (*per Metric*)**

#### **Number of nodes**

In [4]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-number_of_nodes.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
1,angular_separation,"(0, 0.0654)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
2,angular_separation,"(0, 0.1799)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
3,bhattacharyya,"(0, 1.5158)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
4,bhattacharyya,"(0, 2.4304)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
5,bhattacharyya,"(0, 3.6452)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
6,canberra,"(0, 0.6155)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
7,canberra,"(0, 1.0142)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
8,canberra,"(0, 1.4712)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
9,clark,"(0, 0.4161)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
10,clark,"(0, 0.6813)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
11,clark,"(0, 0.983)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
12,euclidean,"(0, 10.2836)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
13,euclidean,"(0, 16.6132)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
14,euclidean,"(0, 26.242)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
15,lance_williams,"(0, 0.1789)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
16,lance_williams,"(0, 0.3041)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
17,lance_williams,"(0, 0.466)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
18,soergel,"(0, 0.3035)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
19,soergel,"(0, 0.4664)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105
20,soergel,"(0, 0.6357)",4642,5.0,20.836062,14.416573,12.0,17.0,27.0,100.0,2.541441,12.18105

#### **Number of edges**

In [5]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-number_of_edges.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",4642,0.0,88.995045,155.149172,13.0,39.0,91.00,3564.0,6.158021,85.176176
1,angular_separation,"(0, 0.0654)",4642,0.0,163.165446,282.841464,32.0,75.0,168.00,4454.0,5.145852,42.906350
2,angular_separation,"(0, 0.1799)",4642,2.0,233.657475,445.649890,48.0,101.0,252.00,4566.0,5.139756,33.804278
3,bhattacharyya,"(0, 1.5158)",4642,0.0,83.336062,127.860652,23.0,42.0,99.00,1317.0,4.561587,29.335858
4,bhattacharyya,"(0, 2.4304)",4642,5.0,159.662645,289.355435,41.0,76.0,181.75,2730.0,5.379009,36.580056
5,bhattacharyya,"(0, 3.6452)",4642,8.0,237.162645,461.386311,57.0,108.0,266.50,4072.0,5.489178,37.063108
6,canberra,"(0, 0.6155)",4642,0.0,73.515941,155.576869,10.0,27.0,76.00,1843.0,5.712005,43.218298
7,canberra,"(0, 1.0142)",4642,0.0,144.313658,325.722593,25.0,52.0,149.00,3336.0,5.762278,40.128540
8,canberra,"(0, 1.4712)",4642,0.0,217.743430,486.908929,39.0,83.0,227.25,4138.0,5.659133,38.279018
9,clark,"(0, 0.4161)",4642,0.0,74.959716,156.159921,11.0,28.0,76.00,1854.0,5.657406,43.176364
10,clark,"(0, 0.6813)",4642,0.0,146.456484,321.666299,25.0,54.0,150.75,3259.0,5.659572,39.163768
11,clark,"(0, 0.983)",4642,0.0,218.981689,486.356427,39.0,81.0,226.00,4124.0,5.580926,37.409791
12,euclidean,"(0, 10.2836)",4642,9.0,92.222749,100.247006,34.0,60.0,117.00,924.0,3.526806,20.004458
13,euclidean,"(0, 16.6132)",4642,10.0,169.334554,259.991784,50.0,94.0,203.75,2587.0,5.123105,34.952169
14,euclidean,"(0, 26.242)",4642,10.0,250.873330,465.096365,66.0,120.0,292.00,4431.0,5.587155,38.896914
15,lance_williams,"(0, 0.1789)",4642,0.0,71.561611,146.062623,12.0,28.0,75.00,1904.0,5.613628,42.386601
16,lance_williams,"(0, 0.3041)",4642,0.0,144.172124,322.865838,26.0,54.0,148.00,3356.0,5.778321,40.306634
17,lance_williams,"(0, 0.466)",4642,2.0,218.840801,490.595162,41.0,84.0,227.00,4087.0,5.701232,38.725741
18,soergel,"(0, 0.3035)",4642,0.0,71.560750,146.058010,12.0,28.0,75.00,1904.0,5.613414,42.383471
19,soergel,"(0, 0.4664)",4642,0.0,144.181603,322.898977,26.0,54.0,148.00,3356.0,5.778353,40.306260
20,soergel,"(0, 0.6357)",4642,2.0,218.818613,490.545857,41.0,84.0,227.00,4087.0,5.701274,38.726352

#### **Density**

In [6]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-density.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",4642,0.000000,0.278462,0.181959,0.133333,0.243590,0.415789,0.804233,0.493822,2.244772
1,angular_separation,"(0, 0.0654)",4642,0.000000,0.519395,0.197734,0.361382,0.524815,0.695238,0.973684,-0.170679,2.121214
2,angular_separation,"(0, 0.1799)",4642,0.133333,0.722692,0.150317,0.621212,0.742669,0.842857,1.000000,-0.548076,2.840747
3,bhattacharyya,"(0, 1.5158)",4642,0.000000,0.314060,0.066612,0.270833,0.321429,0.358974,0.600000,-0.201760,3.166548
4,bhattacharyya,"(0, 2.4304)",4642,0.228612,0.573685,0.083782,0.523810,0.571429,0.630389,0.900000,-0.078851,3.379943
5,bhattacharyya,"(0, 3.6452)",4642,0.482235,0.804806,0.084659,0.746078,0.805263,0.861044,1.000000,-0.110762,3.338408
6,canberra,"(0, 0.6155)",4642,0.000000,0.196889,0.090938,0.133333,0.206240,0.268421,0.508503,-0.307205,2.425895
7,canberra,"(0, 1.0142)",4642,0.000000,0.389423,0.115679,0.323810,0.411600,0.472527,0.727368,-0.800769,3.554430
8,canberra,"(0, 1.4712)",4642,0.000000,0.608497,0.107915,0.555556,0.619048,0.669670,1.000000,-0.645999,4.869060
9,clark,"(0, 0.4161)",4642,0.000000,0.203041,0.096669,0.133333,0.209150,0.280767,0.524660,-0.218662,2.282876
10,clark,"(0, 0.6813)",4642,0.000000,0.400777,0.125420,0.322689,0.424837,0.500000,0.717193,-0.753454,3.160532
11,clark,"(0, 0.983)",4642,0.000000,0.594513,0.135348,0.530303,0.622222,0.687343,0.908399,-1.094953,4.406718
12,euclidean,"(0, 10.2836)",4642,0.099669,0.482904,0.197597,0.326203,0.437908,0.595588,1.000000,0.669106,2.725732
13,euclidean,"(0, 16.6132)",4642,0.191445,0.721183,0.190267,0.567251,0.712121,0.892147,1.000000,-0.067456,1.948904
14,euclidean,"(0, 26.242)",4642,0.315399,0.902825,0.119016,0.833333,0.955214,1.000000,1.000000,-1.261488,4.099339
15,lance_williams,"(0, 0.1789)",4642,0.000000,0.198205,0.073468,0.156952,0.211703,0.248366,0.500000,-0.647476,3.485879
16,lance_williams,"(0, 0.3041)",4642,0.000000,0.407298,0.082098,0.367823,0.411765,0.452632,0.800000,-0.253510,4.745810
17,lance_williams,"(0, 0.466)",4642,0.200000,0.630378,0.088301,0.578465,0.625000,0.666667,1.000000,0.589972,4.925205
18,soergel,"(0, 0.3035)",4642,0.000000,0.198203,0.073467,0.156952,0.211703,0.248366,0.500000,-0.647452,3.485949
19,soergel,"(0, 0.4664)",4642,0.000000,0.407322,0.082078,0.367823,0.411765,0.452632,0.800000,-0.252834,4.747790
20,soergel,"(0, 0.6357)",4642,0.200000,0.630305,0.088315,0.577871,0.624812,0.666667,1.000000,0.589707,4.923444

#### **Betweenness centrality**

In [7]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-betweenness_centrality.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",4642,0.0,0.023856,0.024564,0.006946,0.017483,0.033314,0.314286,2.363850,13.669719
1,angular_separation,"(0, 0.0654)",4642,0.0,0.026980,0.039571,0.005719,0.014652,0.032051,0.333333,3.761526,21.663931
2,angular_separation,"(0, 0.1799)",4642,0.0,0.025018,0.043815,0.002992,0.009194,0.023756,0.333333,3.321100,15.977182
3,bhattacharyya,"(0, 1.5158)",4642,0.0,0.051631,0.029052,0.031882,0.046784,0.065934,0.333333,1.918155,11.044234
4,bhattacharyya,"(0, 2.4304)",4642,0.0,0.040147,0.024410,0.023303,0.033333,0.051282,0.233333,1.951633,9.896436
5,bhattacharyya,"(0, 3.6452)",4642,0.0,0.014103,0.008375,0.008246,0.011864,0.019608,0.066667,1.012283,4.978711
6,canberra,"(0, 0.6155)",4642,0.0,0.024766,0.017927,0.012520,0.022522,0.033626,0.138889,1.000433,4.631061
7,canberra,"(0, 1.0142)",4642,0.0,0.022098,0.013974,0.013140,0.018648,0.028571,0.116667,1.468412,6.515816
8,canberra,"(0, 1.4712)",4642,0.0,0.022823,0.022912,0.009942,0.016217,0.027106,0.266667,3.251835,17.779311
9,clark,"(0, 0.4161)",4642,0.0,0.022613,0.017051,0.010606,0.020189,0.031455,0.119048,1.123452,5.104897
10,clark,"(0, 0.6813)",4642,0.0,0.018812,0.012889,0.010746,0.016071,0.024075,0.133333,1.764990,8.997639
11,clark,"(0, 0.983)",4642,0.0,0.008068,0.007365,0.003497,0.006140,0.010895,0.100000,2.374862,15.054220
12,euclidean,"(0, 10.2836)",4642,0.0,0.052166,0.022691,0.035088,0.048225,0.071429,0.102369,0.071124,2.072906
13,euclidean,"(0, 16.6132)",4642,0.0,0.017788,0.012419,0.008333,0.016850,0.027040,0.051490,0.313789,2.169875
14,euclidean,"(0, 26.242)",4642,0.0,0.004508,0.005173,0.000000,0.002183,0.008030,0.027199,0.963689,2.972201
15,lance_williams,"(0, 0.1789)",4642,0.0,0.037750,0.032969,0.020029,0.031192,0.048257,0.333333,3.873584,28.709395
16,lance_williams,"(0, 0.3041)",4642,0.0,0.042749,0.040157,0.021761,0.032234,0.046154,0.333333,3.793472,21.989739
17,lance_williams,"(0, 0.466)",4642,0.0,0.028002,0.026857,0.013158,0.021429,0.032634,0.333333,4.034976,29.781774
18,soergel,"(0, 0.3035)",4642,0.0,0.037750,0.032969,0.020029,0.031192,0.048257,0.333333,3.873604,28.709595
19,soergel,"(0, 0.4664)",4642,0.0,0.042746,0.040158,0.021761,0.032234,0.046154,0.333333,3.793423,21.988963
20,soergel,"(0, 0.6357)",4642,0.0,0.028012,0.026861,0.013158,0.021429,0.032634,0.333333,4.032783,29.759908

#### **Closeness Centrality**

In [8]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-closeness_centrality.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",4642,0.000000,0.330454,0.191315,0.184358,0.314069,0.484395,0.812909,0.138380,2.075428
1,angular_separation,"(0, 0.0654)",4642,0.000000,0.570887,0.182955,0.455291,0.582716,0.718117,0.976542,-0.496259,2.797818
2,angular_separation,"(0, 0.1799)",4642,0.133333,0.764803,0.124417,0.691148,0.778318,0.855761,1.000000,-0.722682,3.796980
3,bhattacharyya,"(0, 1.5158)",4642,0.000000,0.404978,0.066580,0.371670,0.413438,0.447935,0.680916,-0.878482,5.025740
4,bhattacharyya,"(0, 2.4304)",4642,0.379964,0.664472,0.069794,0.617183,0.660173,0.710968,0.920000,0.033271,3.376465
5,bhattacharyya,"(0, 3.6452)",4642,0.589652,0.849444,0.064108,0.802910,0.851698,0.892045,1.000000,-0.096646,3.270965
6,canberra,"(0, 0.6155)",4642,0.000000,0.246247,0.111858,0.169665,0.268578,0.334614,0.527104,-0.511445,2.417122
7,canberra,"(0, 1.0142)",4642,0.000000,0.450116,0.125988,0.392702,0.479108,0.536546,0.760401,-1.073085,4.188738
8,canberra,"(0, 1.4712)",4642,0.000000,0.672162,0.100936,0.623376,0.681923,0.730782,1.000000,-0.991499,6.215374
9,clark,"(0, 0.4161)",4642,0.000000,0.249828,0.116053,0.166747,0.267589,0.344443,0.531630,-0.435077,2.291515
10,clark,"(0, 0.6813)",4642,0.000000,0.454189,0.134277,0.384374,0.486072,0.552085,0.761099,-0.995374,3.704292
11,clark,"(0, 0.983)",4642,0.000000,0.621038,0.137598,0.560206,0.650812,0.716940,0.912341,-1.196942,4.629034
12,euclidean,"(0, 10.2836)",4642,0.150880,0.583984,0.171873,0.445225,0.558655,0.696555,1.000000,0.399166,2.447496
13,euclidean,"(0, 16.6132)",4642,0.283372,0.785537,0.148027,0.671356,0.786408,0.911976,1.000000,-0.211343,2.248231
14,euclidean,"(0, 26.242)",4642,0.418618,0.924451,0.090328,0.869338,0.961538,1.000000,1.000000,-1.257191,4.337337
15,lance_williams,"(0, 0.1789)",4642,0.000000,0.253089,0.095097,0.205321,0.271029,0.317197,0.610794,-0.691519,3.469047
16,lance_williams,"(0, 0.3041)",4642,0.000000,0.482666,0.092459,0.438130,0.486978,0.527993,0.853333,-0.339807,4.824293
17,lance_williams,"(0, 0.466)",4642,0.233333,0.693980,0.081886,0.642224,0.688647,0.732403,1.000000,0.281666,4.539438
18,soergel,"(0, 0.3035)",4642,0.000000,0.253088,0.095096,0.205321,0.271029,0.317197,0.610794,-0.691504,3.469038
19,soergel,"(0, 0.4664)",4642,0.000000,0.482684,0.092451,0.438130,0.486978,0.527993,0.853333,-0.339599,4.825154
20,soergel,"(0, 0.6357)",4642,0.233333,0.693929,0.081899,0.642224,0.688607,0.732403,1.000000,0.281193,4.538379

#### **Degree Centrality**

In [9]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-degree_centrality.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",4642,0.000000,0.278462,0.181959,0.133333,0.243590,0.415789,0.804233,0.493822,2.244772
1,angular_separation,"(0, 0.0654)",4642,0.000000,0.519395,0.197734,0.361382,0.524815,0.695238,0.973684,-0.170679,2.121214
2,angular_separation,"(0, 0.1799)",4642,0.133333,0.722692,0.150317,0.621212,0.742669,0.842857,1.000000,-0.548076,2.840747
3,bhattacharyya,"(0, 1.5158)",4642,0.000000,0.314060,0.066612,0.270833,0.321429,0.358974,0.600000,-0.201760,3.166548
4,bhattacharyya,"(0, 2.4304)",4642,0.228612,0.573685,0.083782,0.523810,0.571429,0.630389,0.900000,-0.078851,3.379943
5,bhattacharyya,"(0, 3.6452)",4642,0.482235,0.804806,0.084659,0.746078,0.805263,0.861044,1.000000,-0.110762,3.338408
6,canberra,"(0, 0.6155)",4642,0.000000,0.196889,0.090938,0.133333,0.206240,0.268421,0.508503,-0.307205,2.425895
7,canberra,"(0, 1.0142)",4642,0.000000,0.389423,0.115679,0.323810,0.411600,0.472527,0.727368,-0.800769,3.554430
8,canberra,"(0, 1.4712)",4642,0.000000,0.608497,0.107915,0.555556,0.619048,0.669670,1.000000,-0.645999,4.869060
9,clark,"(0, 0.4161)",4642,0.000000,0.203041,0.096669,0.133333,0.209150,0.280767,0.524660,-0.218662,2.282876
10,clark,"(0, 0.6813)",4642,0.000000,0.400777,0.125420,0.322689,0.424837,0.500000,0.717193,-0.753454,3.160532
11,clark,"(0, 0.983)",4642,0.000000,0.594513,0.135348,0.530303,0.622222,0.687343,0.908399,-1.094953,4.406718
12,euclidean,"(0, 10.2836)",4642,0.099669,0.482904,0.197597,0.326203,0.437908,0.595588,1.000000,0.669106,2.725732
13,euclidean,"(0, 16.6132)",4642,0.191445,0.721183,0.190267,0.567251,0.712121,0.892147,1.000000,-0.067456,1.948904
14,euclidean,"(0, 26.242)",4642,0.315399,0.902825,0.119016,0.833333,0.955214,1.000000,1.000000,-1.261488,4.099339
15,lance_williams,"(0, 0.1789)",4642,0.000000,0.198205,0.073468,0.156952,0.211703,0.248366,0.500000,-0.647476,3.485879
16,lance_williams,"(0, 0.3041)",4642,0.000000,0.407298,0.082098,0.367823,0.411765,0.452632,0.800000,-0.253510,4.745810
17,lance_williams,"(0, 0.466)",4642,0.200000,0.630378,0.088301,0.578465,0.625000,0.666667,1.000000,0.589972,4.925205
18,soergel,"(0, 0.3035)",4642,0.000000,0.198203,0.073467,0.156952,0.211703,0.248366,0.500000,-0.647452,3.485949
19,soergel,"(0, 0.4664)",4642,0.000000,0.407322,0.082078,0.367823,0.411765,0.452632,0.800000,-0.252834,4.747790
20,soergel,"(0, 0.6357)",4642,0.200000,0.630305,0.088315,0.577871,0.624812,0.666667,1.000000,0.589707,4.923444

#### **Eigenvector Centrality**

In [10]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-eigenvector_centrality.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",75,0.056549,0.112677,0.052045,0.073324,0.096721,0.129756,0.275995,1.343132,4.122541
1,angular_separation,"(0, 0.0654)",841,0.075181,0.186058,0.069698,0.138871,0.168531,0.227650,0.441019,0.911612,3.822644
2,angular_separation,"(0, 0.1799)",2345,0.094930,0.231531,0.071200,0.172541,0.222929,0.276523,0.447214,0.481527,2.877713
3,bhattacharyya,"(0, 1.5158)",235,0.071314,0.155537,0.074466,0.100658,0.131960,0.190786,0.390316,1.283709,4.071868
4,bhattacharyya,"(0, 2.4304)",4128,0.073417,0.231826,0.071727,0.174150,0.221917,0.268999,0.445276,0.559443,2.995418
5,bhattacharyya,"(0, 3.6452)",4641,0.090629,0.243838,0.071238,0.187158,0.234042,0.280428,0.447214,0.535580,3.030428
6,canberra,"(0, 0.6155)",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,canberra,"(0, 1.0142)",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,canberra,"(0, 1.4712)",1044,0.095124,0.211779,0.074026,0.158668,0.195425,0.252808,0.447214,0.795742,3.161355
9,clark,"(0, 0.4161)",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,clark,"(0, 0.6813)",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,clark,"(0, 0.983)",1,0.387738,0.387738,NaN,0.387738,0.387738,0.387738,0.387738,NaN,NaN
12,euclidean,"(0, 10.2836)",4641,0.065371,0.234820,0.076566,0.176420,0.228331,0.276684,0.447214,0.460360,2.888069
13,euclidean,"(0, 16.6132)",4642,0.075388,0.243928,0.073568,0.185426,0.234271,0.283268,0.447214,0.468897,2.932775
14,euclidean,"(0, 26.242)",4642,0.090048,0.248053,0.071604,0.191057,0.239869,0.288147,0.447214,0.469157,2.953436
15,lance_williams,"(0, 0.1789)",250,0.070122,0.149052,0.069672,0.097116,0.130331,0.185904,0.430940,1.582132,5.931116
16,lance_williams,"(0, 0.3041)",988,0.083905,0.205155,0.081898,0.146499,0.181272,0.247169,0.441019,0.869620,2.998084
17,lance_williams,"(0, 0.466)",1962,0.093743,0.231527,0.080000,0.165402,0.215854,0.286877,0.447214,0.612064,2.604904
18,soergel,"(0, 0.3035)",250,0.070122,0.149052,0.069672,0.097116,0.130331,0.185904,0.430940,1.582137,5.931133
19,soergel,"(0, 0.4664)",988,0.083916,0.205157,0.081897,0.146499,0.181272,0.247169,0.441019,0.869682,2.998161
20,soergel,"(0, 0.6357)",1962,0.093743,0.231524,0.080001,0.165402,0.215854,0.286877,0.447214,0.612098,2.604967

#### **Harmonic Centrality**

In [11]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-harmonic_centrality.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",4642,0.000000,8.450968,7.848910,3.002381,6.738889,11.066611,80.875421,1.848560,8.558531
1,angular_separation,"(0, 0.0654)",4642,0.000000,13.290245,10.688327,6.533333,10.631944,17.044960,91.050505,2.078664,9.594394
2,angular_separation,"(0, 0.1799)",4642,0.666667,16.689544,12.810670,8.916667,13.388889,21.847701,95.114478,2.403107,11.390581
3,bhattacharyya,"(0, 1.5158)",4642,0.000000,9.940861,7.226963,5.576049,8.060481,12.910728,53.095582,2.337706,11.386864
4,bhattacharyya,"(0, 2.4304)",4642,2.200000,14.704521,10.157117,8.625107,12.027348,18.899359,74.832302,2.597437,12.942492
5,bhattacharyya,"(0, 3.6452)",4642,3.333333,17.592434,12.482539,10.282051,14.362745,22.815773,90.051020,2.671336,13.285906
6,canberra,"(0, 0.6155)",4642,0.000000,7.073397,7.448435,2.481481,5.078105,9.264482,57.478351,2.748601,13.864071
7,canberra,"(0, 1.0142)",4642,0.000000,11.328521,10.638264,5.092308,8.341667,14.971889,79.518900,2.859703,14.577379
8,canberra,"(0, 1.4712)",4642,0.000000,15.357629,13.088031,7.638889,11.722222,20.350575,90.557895,2.824424,14.148604
9,clark,"(0, 0.4161)",4642,0.000000,7.065769,7.359913,2.448718,5.048889,9.241726,56.271478,2.642660,13.150963
10,clark,"(0, 0.6813)",4642,0.000000,11.289718,10.523020,5.058333,8.422222,14.896154,78.575258,2.755275,13.837251
11,clark,"(0, 0.983)",4642,0.000000,14.218272,12.815444,6.769231,10.722222,18.946429,88.539519,2.785959,13.902237
12,euclidean,"(0, 10.2836)",4642,3.166667,12.230860,6.271684,7.923077,10.692308,15.079841,51.103741,2.082034,10.235991
13,euclidean,"(0, 16.6132)",4642,4.000000,15.806035,9.591873,9.769231,13.400000,20.158156,74.697279,2.437771,12.283650
14,euclidean,"(0, 26.242)",4642,4.000000,18.340749,12.425403,11.000000,15.000000,23.895628,93.714286,2.617611,13.248124
15,lance_williams,"(0, 0.1789)",4642,0.000000,7.436749,7.595963,2.901190,5.354167,9.777509,58.427491,2.889924,14.816567
16,lance_williams,"(0, 0.3041)",4642,0.000000,12.132270,10.805960,5.861111,9.109127,15.834808,81.027491,2.960957,15.174525
17,lance_williams,"(0, 0.466)",4642,1.000000,15.718912,12.982573,8.025641,12.093464,20.580833,90.021053,2.899828,14.634996
18,soergel,"(0, 0.3035)",4642,0.000000,7.436728,7.595921,2.901190,5.354167,9.777509,58.427491,2.889877,14.816147
19,soergel,"(0, 0.4664)",4642,0.000000,12.132572,10.806364,5.861111,9.109127,15.834808,81.027491,2.961047,15.175012
20,soergel,"(0, 0.6357)",4642,1.000000,15.718171,12.981976,8.025641,12.093464,20.580833,90.021053,2.899810,14.634999

#### **Number of Connected Components**

In [12]:
pd.read_csv(
    app.graph_analysis['graph_metrics_summary'].with_name(
        app.graph_analysis['graph_metrics_summary'].name + "-number_of_connected_components.csv"
    )
)

,distance_function,interval,count,min,mean,std,p25,p50,p75,max,skewness,kurtosis
0,angular_separation,"(0, 0.018)",4642,1.0,4.912969,1.893458,3.0,5.0,6.0,14.0,0.498305,3.303567
1,angular_separation,"(0, 0.0654)",4642,1.0,2.574106,1.068542,2.0,3.0,3.0,7.0,0.268837,2.776359
2,angular_separation,"(0, 0.1799)",4642,1.0,1.538130,0.580468,1.0,1.0,2.0,4.0,0.555431,2.506898
3,bhattacharyya,"(0, 1.5158)",4642,1.0,2.688496,0.803940,2.0,3.0,3.0,6.0,0.083543,2.570823
4,bhattacharyya,"(0, 2.4304)",4642,1.0,1.110728,0.313829,1.0,1.0,1.0,2.0,2.481057,7.155644
5,bhattacharyya,"(0, 3.6452)",4642,1.0,1.000215,0.014677,1.0,1.0,1.0,2.0,68.110206,4640.000215
6,canberra,"(0, 0.6155)",4642,2.0,6.125377,1.825094,5.0,6.0,7.0,17.0,0.806143,4.147186
7,canberra,"(0, 1.0142)",4642,2.0,3.922878,0.975502,3.0,4.0,4.0,9.0,0.532051,3.653068
8,canberra,"(0, 1.4712)",4642,1.0,2.028221,0.713900,2.0,2.0,2.0,6.0,0.239660,2.804468
9,clark,"(0, 0.4161)",4642,2.0,6.198837,1.854284,5.0,6.0,7.0,17.0,0.773924,3.972241
10,clark,"(0, 0.6813)",4642,2.0,4.111374,1.046579,3.0,4.0,5.0,9.0,0.521107,3.578166
11,clark,"(0, 0.983)",4642,1.0,3.425894,0.735560,3.0,3.0,4.0,6.0,-0.217603,2.738839
12,euclidean,"(0, 10.2836)",4642,1.0,1.000215,0.014677,1.0,1.0,1.0,2.0,68.110206,4640.000215
13,euclidean,"(0, 16.6132)",4642,1.0,1.000000,0.000000,1.0,1.0,1.0,1.0,NaN,NaN
14,euclidean,"(0, 26.242)",4642,1.0,1.000000,0.000000,1.0,1.0,1.0,1.0,NaN,NaN
15,lance_williams,"(0, 0.1789)",4642,1.0,5.215640,1.801932,4.0,5.0,6.0,11.0,-0.331855,3.136047
16,lance_williams,"(0, 0.3041)",4642,1.0,2.658121,1.051613,2.0,3.0,3.0,6.0,-0.309352,2.185355
17,lance_williams,"(0, 0.466)",4642,1.0,1.636579,0.591528,1.0,2.0,2.0,3.0,0.318899,2.313750
18,soergel,"(0, 0.3035)",4642,1.0,5.215640,1.801932,4.0,5.0,6.0,11.0,-0.331855,3.136047
19,soergel,"(0, 0.4664)",4642,1.0,2.658121,1.051613,2.0,3.0,3.0,6.0,-0.309352,2.185355
20,soergel,"(0, 0.6357)",4642,1.0,1.636579,0.591528,1.0,2.0,2.0,3.0,0.318899,2.313750